# Generated by Django 5.0.4 on 2024-04-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BondModel',
            fields=[
                ('bond_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date_of_purchase', models.DateField()),
                ('name_of_purchaser', models.TextField()),
                ('date_of_expiry', models.DateField()),
                ('name_of_political_party', models.TextField()),
                ('date_of_encashment', models.DateField()),
                ('denomination', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
