# Generated by Django 5.0.4 on 2024-04-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bonds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bondmodel',
            name='short_name',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
