# Generated by Django 5.0.4 on 2024-04-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bonds', '0003_alter_bondmodel_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bondmodel',
            name='short_name',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
