# Generated by Django 5.0.4 on 2024-04-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acmodel',
            name='image_data',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
