# Generated by Django 5.0.4 on 2024-04-23 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_listitem_remove_acmodel_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acmodel',
            name='list_image',
            field=models.ManyToManyField(to='authentication.listitem'),
        ),
    ]
