# Generated by Django 5.0.4 on 2024-04-25 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_acmodel_list_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 25, 10, 7, 31, 664327, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
