# Generated by Django 5.0.4 on 2024-04-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_remove_comment_id_comment_comment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='acmodel',
            name='author',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='acmodel',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
