# Generated by Django 5.0.4 on 2024-05-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_acmodel_author_acmodel_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acmodel',
            name='list_image',
        ),
        migrations.AddField(
            model_name='acmodel',
            name='subtitle',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='acmodel',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.DeleteModel(
            name='ListItem',
        ),
    ]
