# Generated by Django 5.0.4 on 2024-05-04 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_imageupload_articleid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageupload',
            name='articleid',
        ),
    ]
